---
title: Wissenschaftliche Methodik -- \newline Übung Quantitative Datenanalyse mit R
author: "erstellt von Professor*innen des ifes"
date: "SoSe 2023"
lang: de-De
colorlinks: yes
template: NULL
documentclass: scrreprt
classoption: 
    - paper=a4
    - pagesize
    - DIV=13  # oder 14
link-citations: yes
fontsize: 12pt
output:
  pdf_document:
    includes:
      in_header: preamble.tex
    latex_engine: pdflatex
    keep_tex: yes
    template: NULL
    pandoc_args:
        - --standalone
        - --filter
        - ./pandocfilter/typography.py
        - -V
        - graphics=TRUE
    fig_height: 3
    fig_width: 5
  html_document:
    fig_height: 3
    fig_width: 5
  word_document:
    fig_height: 3
    fig_width: 5
---

\tableofcontents
\newpage 

<!-- \fancyhead[LO,RE]{\textsl{\rightmark}}   -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Initiale Paket Installation
needed_pkgs <- c("mosaic", "corrplot", 
                 "lsr", "effects", "ModelMetrics",
                 "ROCR", "lmtest", "BaylorEdPsych",
                 "gplots","nFactors", "scatterplot3d",
                 "tidyverse", "stringr", "car", "okcupiddata", 
                 "knitr", "nycflights13")
new.pkgs <- needed_pkgs[!(needed_pkgs %in% installed.packages())]

if(length(new.pkgs)) {
  install.packages(new.pkgs, repos = "https://cran.rstudio.com")
}


require(mosaic)
require(corrplot)
kap <- -1
anh <- 0
```

```{r child = 'Inhalte/ErsteSchritte.Rmd', eval = TRUE}
```

\newpage

```{r child = 'Inhalte/EinfuehrungDaten.Rmd', eval = TRUE}
```

\newpage

```{r child = 'Inhalte/EinfuehrungWkeitInferenz.Rmd', eval = TRUE}
```

\newpage

```{r child = 'Inhalte/Inferenz-Kategorial.Rmd', eval = TRUE}
```

\newpage

```{r child = 'Inhalte/Inferenz-Metrisch.Rmd', eval = TRUE}
```

\newpage

```{r child = 'Inhalte/Regression.Rmd', eval = TRUE}
```

\newpage

```{r child = 'Inhalte/LogRegression.Rmd', eval = TRUE}
```

\newpage

```{r child = 'Inhalte/Dimensionsreduktion-PCA-EFA.Rmd', eval = TRUE}
```

\newpage

```{r child = 'Inhalte/Clusteranalyse.Rmd', eval = TRUE}
```

\newpage

```{r child = 'Inhalte/R-mosaic-Kurzreferenz.Rmd', eval = TRUE}
```

\newpage

```{r child = 'Inhalte/Datenjudo.Rmd', eval = TRUE}
```

\newpage

```{r child = 'Inhalte/Daten_visualisieren.Rmd', eval = TRUE}
```